### ISSUE TITLE
Make package conditions in obs service more expressive

### ISSUE THREAD

**Issue by schaefi** [SUSE-Enceladus/mash#194]
The obs service allows to specify min and max version of a package as a condition.
However it could be done in a more expressive way as suggested by Sean:

``` json
"conditions": [
      {"name": "cool_package", "lower_bound": "1.0.0", "upper_bound": "2.0.0"},
      {"image": "version"}
]
```

**Comment by smarlowucf** [comment]
Actually I misunderstood the current implementation. I like it except it could be like:

```
"conditions": [
      {"name": "cool_package", "version": ">=1.0.0", "release": ">=2.0.0"},
      {"image": "version"}
]
```

This way the args are not forced to a certain order and the names add some documentation to what each value is.

**Comment by rjschwei** [comment]
> Actually I misunderstood the current implementation. I like it except it could be like:
> 
> ```
> "conditions": [
>       {"name": "cool_package", "version": ">=1.0.0", "release": ">=2.0.0"},
>       {"image": "version"}
> ]
> ```
OK, "version" is clear and unmistakable, but "release" I think is ambiguous, consider a common versioning scheme

Major.Minor.Release

But in our case "release" is supposed to be the build number. Also "Release:" shows up in spec file but is generally set to 0 so OBS can do its magic. If we take the kernel for example then we have:

kernel-default-4.4.143-65.1.x86_64

So 4.4.143 is the version, i.e. Major.Minor.Release and 65.1 is also "release" according to the proposal. I would prefer that we call it "build-number" or "package-build" or "build" or "build-id", or something along these lines.

**Comment by schaefi** [comment]
When I have done this version and release were inherited from how RPM defines it:

```
Version:  ...
Release:   ...
```

both information could be relatively complex and can include numbers as well as characters. There is no reliable format you can trust in this regard. As an example see:

* https://build.opensuse.org/package/view_file/openSUSE:Factory/vim/vim.spec?expand=1

many packages never set a release and the buildservice itself iirc also appends a build number

Therefore I agree with Robert. We should not distinguish between version and release and just introduce one matcher e.g

``` json
"conditions": [
      {"name": "cool_package", "package-id": "..."},
      {"image": "version"}
]
```

The problem I see is that in my former implementation I tried to provide a feature to allow
saying "if this package has a version greater than X" After I had a closer look how we at suse create the packages and that there are basically no rules how to specify the version I came to the conclusion that this code will be very unstable and not reliable

I think the only number match if we want that is the build number the build service appends. However we only see the complete package name and it's also not easy to clearly identify the build number. In addition the build number is not incremental it is reset with any change in Version: or Release: of the spec file.

So what has turned out to be easy is not easy at all.

Maybe within the scope of mash we also don't need that much magic ?

**Comment by rjschwei** [comment]
Well we do need some kind of magic. I think we should stick to the most common example where we really needs this functionality, security updates in the kernel, glibc. These packages have "sane" numbering and via internal e-mail we will be informed that fix for CVE-X will be in kernel-default-*. I definitely want us to be able to catch this.

Whether we have one entry as in "package-id" that takes the form of "4.4.155-68.1" and we accept this and later builds or we have two entries such as "version: 4.4.155, build-id: 68.1" is somewhat immaterial. Basically means we decide if we want the user to handle the '-' or if we'll do that in code.

The other likely candidate, the ssl library, has a letter in the version number, such as "1.0.2j-25.1" so we will need to handle letters and understand that "1.0.0k" > "1.0.2j"

**Comment by smarlowucf** [comment]
Okay so if we just care about version then do we prefer a single option still?

```
"conditions": [
      {"name": "cool_package", "version": ">=1.0.0j"}
]
```

Or make it explicit:

```
"conditions": [
      {"name": "cool_package", "version": "1.0.0j", "expression": ">="}
]
```

The comparison issue is solved already:

```
>>> from pkg_resources import parse_version
>>> parse_version('1.0.0k') >= parse_version('1.0.0j')
True
```

The example doesn't make sense though. `"1.0.0k" > "1.0.2j"` should be false since 0 is less than 2 prior to comparison of k and j. Looking at openssl it would go 1.0.2j to 1.0.2k.

**Comment by rjschwei** [comment]
OK, parse_version also handles '-' as in "4.12.14-25.13.1" thus I am OK with just having one identifier.

I propose

`"conditions": [
      {"name": "cool_package", "version": "1.0.0j-68.3", "condition": ">="}
]`

or

`"conditions": [
      {"name": "cool_package", "version": "1.0.0j-68.3", "requirement": ">="}
]`

**Comment by smarlowucf** [comment]
If the numbers after the dash are an OBS build number. How will one know what the version should be? It seems like the package version is only certain. Build number really is a pointless number. It doesn't give the info needed.

Say a package is at 1.0.0j-68.3 and we want the first 1.0.1 release. How will we know what to check for?

Will it be 1.0.1-69.1 or 1.0.1a-68.4 or 1.0.1a-70.1? I think the build number isn't important. Really it's the package version that matters (1.0.1 or 1.0.1a). And anything after the dash causes problems:

```
>>> parse_version('1.0.1a-70.1') >= parse_version('1.0.1')
False
```

This of course should pass but doesn't. Why should a user have to know/guess a build number? Builds don't necessarily relate to a new version of the package.

```
>>> parse_version('1.0.1a-70.1') >= parse_version('1.0.1a-69.0')
True
```

If it's possible for the package version itself to have a dash then we can still easily split the build service number and only compare a version:

```
target = '1.0.1-dev'
current = '1.0.2-dev-69.1'
current = current.rsplit('-', maxsplit=1)[0]  # 1.0.2-dev

>>> parse_version(current) >= parse_version(target)
True
```

I think this is more user friendly and makes the condition check less error prone.

**Comment by smarlowucf** [comment]
@rjschwei @schaefi 

Given the previous comments any thoughts for/against going with:

```
"conditions": [ {"name": "cool_package", "version": "1.0.0j", "condition": ">="} ]
```

Where version is just the package version? As stated above I don't think a build number is helpful or useful in determining a package version.

**Comment by rjschwei** [comment]
> If the numbers after the dash are an OBS build number. How will one know what the version should be?

Because we will be told that a fix we are looking for will be in a certain build.

> It seems like the package version is only certain. Build number really is a pointless numberin this case, no?

Nope, the build number is actually the most important part. For example the kernel version ins a given SP never changes, for SLES 15 the kernel version is 4.12.14. However we would need to know what build contains a certain fix. Thus whether it is 4.12.14-25.13.1 or 4.12.14-38.1.1 is very important.


> It doesn't give the info needed (that a specific version of a package as built).
> 
> Say a package is at 1.0.0j-68.3 and we want the first 1.0.1 release. How will we know what to check for?
> 
> Will it be 1.0.1a-69.1 or 1.0.1a-68.4 or 1.0.1a-70.1?

Well if we just need 1.0.1 then any of your examples would do and we'd take the first image that meets >= 1.0.1

> I think the build number isn't important.

The build number is very important

> Really it's the package version that matters (1.0.1a).

The package version less so, for the SLES model of distribution updates. If we look at openSUSE the model is a bit different and there package version numbers would have more relevance, correct.

> And anything after the dash causes problems:
> 
> ```
> >>> parse_version('1.0.1a-70.1') >= parse_version('1.0.1a')
> False
> ```
> This of course should pass but doesn't. Why should a user have to know/guess a build number? Builds don't necessarily relate to a new version of the package.

Not necessarily correct, but new build do not preclude a "new package with new patches". It's a "fuzzy" condition. Good catch with the test, we'll have to write our own version parser, or we can split "version" and "build-id" and then compare both with parse_version(), that will probably work.

**Comment by rjschwei** [comment]
> @rjschwei @schaefi
> 
> Given the previous comments any thoughts for/against going with:
> 
> ```
> "conditions": [ {"name": "cool_package", "version": "1.0.0j", "condition": ">="} ]
> ```
> Where version is just the package version? As stated above I don't think a build number is helpful or useful in determining a package version.

Sorry I missed commenting on the longer comment, that's now done, hopefully that clarifies the situation. The comparison must include the build number.

But to make it more "user friendly" and force less of "the way we do things" into mash I would suggest to split things apart, similar to what we kicked around previously

`"conditions": [ {"name": "cool_package", "version": "1.0.0j", "build-id": "68.3", "condition": ">="} ]`

The code compares on both numbers and if one matches the condition we move on. The logic gets a bit more tricky if there is a '-' in the version itself, but an rsplit() should handle tat for us nicely.

**Comment by smarlowucf** [comment]
> Nope, the build number is actually the most important part. For example the kernel version ins a given SP never changes, for SLES 15 the kernel version is 4.12.14. However we would need to know what build contains a certain fix. Thus whether it is 4.12.14-25.13.1 or 4.12.14-38.1.1 is very important.

Ah, okay. I overlooked this scenario. I like having both options separate than.

```
"conditions": [ {"name": "cool_package", "version": "1.0.0j", "build-id": "68.3", "condition": ">="} ]
```

This looks good and build-id could be optional.
