### ISSUE TITLE
Update MASH for OBS parameter changes

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/mash#253]
OBS is not using API anymore and some parameters have changed:

```json
{
    "obs_job": {
        "id": "123",
        "download_root": "http://download.suse.de/ibs",
        "image": "SLES12-Azure-BYOS",
        "project": "Devel:/PubCloud:/Stable:/Images12",
        "utctime": "now",
        "conditions": [
            {"package": ["kernel-default", ">=4.13.1", ">=1.1"]},
            {"image": "1.42.1"}
        ]
    }
}
```

* image: specifies the name as we set it in the kiwi XML description
* project: specifies an uri path such that it is a valid location, see the :/ notation
* download_root: defaults to the public obs download area, must be set if the project lives somewhere else

Update example messages and job creator to handle these parameters correctly.

**Comment by schaefi** [comment]
@smarlowucf thanks for adding the issue. All the obs changes are now in master. If you want me to adapt them just drop me a note

**Comment by smarlowucf** [comment]
I can make updates for this. download_root is optional right?
