### ISSUE TITLE
Azure Publishing

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/mash#266]
Overview:

With Azure publishing integration there's a few things to consider. The current implementation of testing service and uploader service are good to go. I was unable to launch an image from blob so we will need a temporary image from blob to use. The image will be deleted by testing service prior to publishing.

Questions:
- [x] Given there is no replication do we want to hand the testing service this knowledge (pass azure jobs to publisher) or do we have replication service handles these jobs (do nothing) and pass on to publisher?
- [x] For testing only jobs do we want to cleanup all of the images, snapshots, blobs etc in the cloud accounts?

Backlog
- [x] Handle Azure jobs past testing service according to above decision.
- [x] Stub replication service if necessary.
- [x] Add Azure publisher class and handle publishing steps.
- [x] Determine new requirements for Azure publishing (i.e. requests).
- [x] Update example messages/tests etc.

**Comment by smarlowucf** [comment]
@rjschwei @schaefi Any additions or thoughts?

**Comment by rjschwei** [comment]
Azure should have a replication service implementation. While the service does no active replication work, it should do the monitoring and waiting work. The EC2 implementation of replication waits for the replication to complete before passing the job on to the publisher, so the Azure replication service should behave in the same way, i.e. wait for replication to complete.

Yes we want to clean up, default behavior, with the caveat that the clean up behavior can be overridden in the config and that test failures also skip the cleanup step.

To that extend I have on my list to write an ec2removeimg utility so please do not bake this directly into mash but plan for importing it from ec2utils.
