### ISSUE TITLE
Uploader service halts on SSH connection

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/mash#277]
If there is not a default security group in the region being used by uploader it creates a default group without external SSH access. This causes the uploader sit idle attempting to get a connection.

This is inside the underlying requirement [ec2uploadimg](https://github.com/SUSE/Enceladus/tree/master/ec2utils/ec2uploadimg).

Maybe a default security group in each region with SSH access is expected?

**Comment by schaefi** [comment]
ec2_upload_parameters allows to specify a collection of ```security_group_ids``` which is currently initialized empty. It would be possible to extend the credentials information for EC2 with that information but I think the creation of the security group should be done in the account/role setup of the account we use here.

I did not stumble over that issue in the past and assumed ec2uploadimg starts the helper ami always with a "default" security group which, if not present, would lead to an error on instance launch time. If it sits there and is blocked forever this would be very bad. afaik there is also a timeout for the ssh connection to succeed which is set by the uploader to 300sec

**Comment by smarlowucf** [comment]
I believe we did discuss this and I think this is a good route.

> uploader to 300sec

Once I noticed the delay I fixed the security group so not sure if it had been running more than 5 minutes.

**Comment by rjschwei** [comment]
Hm, a security group created by ec2uploadimg should have the proper settings, the code is as follows:

>         data = self._connect().authorize_security_group_ingress(
>             GroupId=self.security_group_id,
>             IpPermissions=[
>                 {'IpProtocol': 'tcp',
>                  'FromPort': 22,
>                  'ToPort': 22,
>                  'IpRanges': [{'CidrIp': '0.0.0.0/0'}]}
>             ])

The only think I can think of that would trigger the observed behavior is that a group named "default" already existed and that group did not have the proper ingress permissions.

The ec2uploadimg code is not very discriminatory when it comes to handling of the security group. It will take whats in the config file, or what is supplied on the command line, and if nothing is supplied it will try to launch an instance and thus falling back on the EC2 default behavior. The EC2 default behavior is to use a security group named "default".

I think form an ec2uploadimg perspective this is the proper course of action, if you think ec2uploadimg should be more strict in checking that the security group has port 22 open please file a bug against ec2uploadimg.

**Comment by smarlowucf** [comment]
> I think form an ec2uploadimg perspective this is the proper course of action, if you think ec2uploadimg should be more strict in checking that the security group has port 22 open please file a bug against ec2uploadimg.

I think this is good. The SG is needed for uploader and testing service so it couldn't be cleaned up. Thus should probably be a pre condition setup before MASH runs.
