### ISSUE TITLE
OBS Service repository argument

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/mash#287]
OBS service should expose the repository option for retrieving images. Instead of a forced default of `images` it should be configurable in job documents.

E.g. `'repository': ''  # To not append to URL`

or `'repository': 'images'`

**Comment by rjschwei** [comment]
Hmm, this creates a wave for every "standard" setup to accommodate the special case of the "pre GMC phase during distro development". I am not even certain we will follow this path going forward as this has been very painful for SP4 and given today's discussion I am not certain this is going to get any better. I am weary of encoding special cases when they have rather large impact on the "main stream".

If we expose 'repository' we'll end up having to have a "default" behavior which in this case, IMHO, results in non-obvious magic. Then again we have this already with the default of "'https://download.opensuse.org/repositories".

So the question here is, should we be adding more special cases that provide non-obvious defaults or might we be better off dropping things like get_download_root() in obs.defaults and be less considered of special cases.

If we are going down this path we could just as well use the existing "download_root" and make it a more complete path such that the only thing left to add for the code is the image name. We might rename "download_root" to "download_image_url".

**Comment by smarlowucf** [comment]
Already finished the changes. Very easy to change this in MASH (30mins not counting rebuild/versioning etc).

But I would agree that splitting these up into separate fields is mostly pointless.

All of our templates have to override defaults which means 3 args that just get combined to 1 URL.

e.g.

```
"project": "Cloud:Tools",
"download_root": "http://download.opensuse.org/repositories/",
"repository": "images",
```
Gets combined to:
```
self.remote = WebContent(
    os.sep.join([self.download_root, self.project, self.repository])
)
```

I think it'd be easier to just make download_root = download_url and make it required.

```
"download_root": "http://download.opensuse.org/repositories/Cloud:Tools/images"
```
Gets combined to:
```
self.remote = WebContent(
    self.download_url
)
```

Thoughts? @schaefi ?

**Comment by smarlowucf** [comment]
Ref #288

**Comment by smarlowucf** [comment]
Added another branch with fix to handle the Beta build number.

https://github.com/SUSE-Enceladus/mash/compare/obs-build-number?expand=1
