### ISSUE TITLE
OBS conditions should cause a wait rather than auto fail

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/mash#378]
If conditions are supplied for a job and they are not met then the OBS service should wait until they become met to continue with image.

The current implementation fails eagerly if the conditions aren't met and fails the job if it's a one time job.

**Comment by smarlowucf** [comment]
@schaefi 

I thought the conversation was towards waiting on the condition to be met but could likely remember the discussion incorrectly.

Agree that the change means a condition could be never met and a job would never finish. However, the job can be deleted from the client with mash `job delete --job-id='...'`. We don't know when a condition can be met so there can't really be a useful timeout and if conditions are already met it works that same either way.

Don't have a strong opinion if we leave MASH as is or push #380.

Advantage of the change is you can send in a job and it will wait for conditions. All the user has to do is periodically check job status.

In the current implementation you have to keep submitting jobs until conditions are met or manually check the packages/images conditions.

**Comment by smarlowucf** [comment]
@rjschwei Thoughts?

**Comment by rjschwei** [comment]
I also think we had agreed on waiting for the condition. That's what would make sense to me. The whole point of the conditions is that we can release ASAP when for example a kernel hot fix is available in an image build. The point is that no one on the team has to sit up in the middle of the night and watch the image builds and then "push a button"

**Comment by smarlowucf** [comment]
Okay as the PR is approved I will merge the changes.
