### ISSUE TITLE
Need a way to verify an image for inclusion of packages based on license

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#396]
Due to contractual agreements it may be our responsibility to avoid providing images that contain packages with a certain license. We need the ability to specify a conditional that allows us to flag an image as "no releasable" based on license information.

Packages can be dual licensed and thus the code should only error out if and only if a package is single licensed and is of the license specified in the conditional. Names are expected to follow whatever naing convention and are free form, i.e. it is the users responsibility to ensure the specification in the conditional matches whatever the packages use. for SUSE distributions licenses are specified per SPDx for example. Comparison should be case insensitive.

**Comment by rjschwei** [comment]
We want to take advantage of https://github.com/SUSE/kiwi/pull/937 which need to be propagated to active SLE and openSUSE distros

**Comment by smarlowucf** [comment]
Closed by https://github.com/SUSE-Enceladus/mash/pull/644
