### ISSUE TITLE
Progress during image download

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#407]
We should write some progress indicator to the log for image download. Image downloading can take a while and a user tailing the log has no indication if the download dies or if it is still progressing.

**Comment by smarlowucf** [comment]
Looks like you can pass in a hook that notifies after every chunk. Question is how often do we need an update? Since this is a log file we cannot do a progress style update it has to be a new log message with each update.

**Comment by rjschwei** [comment]
Well if we do a "Still uploading, 20% done" message then there would be an indication that something is happening. i.e. a message at 20%, 40%, 60% and 80% should suffice

**Comment by smarlowucf** [comment]
Will be captured by new image downloader package.

**Comment by smarlowucf** [comment]
Related to https://github.com/SUSE-Enceladus/img-downloader/issues/4
