### ISSUE TITLE
For GCE we need a way to set a test project

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#408]
In GCE projects that are used for publishing cannot have any quota, i.e. it is not possible to run an instance in those projects. This triggers a failure in mash as ipa cannot run during the release process. We want a way to specify a test project, i.e. the image gets uploaded to the publishing project but gets tested in some other project.

**Comment by smarlowucf** [comment]
As a note this means a change to the GCE user model. When creating a user you would need to provide two sets of credentials. --upload-credentials and --testing-credentials. The bucket and zone can remain as a single arg.

However, the testing-credentials should be optional still as you may want to run a job in a non-publishing project just for testing. Or for an image that is for use only in that project.

**Comment by smarlowucf** [comment]
Is there a preference in route:

Each account can have a test account which is a name string matching to an existing account and credentials on the MASH instance? This prevents duplication in credentials but is more complicated data structure and maybe more confusing.

or

Each account can have a second set of credentials for testing? I think this is more straightforward but means duplicating credentials. Only have one more optional argument for the testing credentials json.

Either way the account setup changes slightly. In that the testing account only needs vm permissions and the publisher account only needs storage permissions.

**Comment by rjschwei** [comment]
I would have thought the re-use case would be more straight forward. In my mind this change works like this:

The job-doc gets:

```test_account: XYZ```

Then the code does:

```
if job.get('test_account'):
    test_credentials_data = get_credentials(job.get('test_account'))
```

and then somewhere later we use the credentials when we start the test. If test_account is set and there are no credentials we complain and the job fails.

**Comment by smarlowucf** [comment]
That matches the first option. However, failure happens in credentials service before job starts (all accounts/credentials in a job must exist).

**Comment by rjschwei** [comment]
Even better if the submission fails right away.

Yes my thought was option 1, what I didn't get is why you stated it was not straight forward, I mus be missing something.

**Comment by smarlowucf** [comment]
The complication with the first route is that you now have linked rows between data. So handling this adds complications.

- When adding an account with a linked testing account you have to validate that the account exists.
- When deleting any account do we need to go through every other account and delete those that link to it or log a warning?
- Or do we assume data integrity is up to the user?

I think we need to handle all of these issues in code and not leave it up to the user. But this gets complicated if you need a force option now to delete an account and ignore links. Or you just delete it and log a warning/send notification.

**Comment by rjschwei** [comment]
I think you are over thinking it. Yes, I agree that there is a "if this then that conundrum". But, I think this falls under the user responsibility.

The user is responsible for specifying the account to which an image is uploaded. This also implies the user has previously setup that account in mash. At least from the command line we have no option of "check account exists, offer to create if not" work flow. That maybe something we can build into a web-ui if we get there. So just like the user is responsible to create an account the user is responsible for creating the test account in mash if they want to use that configuration option/path.

**Comment by smarlowucf** [comment]
I mean all of it will end in error cases and have to be handled in some fashion. I prefer to handle it in a nice way from a user standpoint. E.g. preventing errors/confusion before they happen.

**Comment by rjschwei** [comment]
I understand the intention, I think. But I fail to see the difference between

```
"cloud_accounts": { "name": "foo" },
```

when foo does not exist and

```
"test_account": "bar"
```

when bar does not exists. The only thing we can tell the user is that the account does not exist. And if we make one check for account existence in the validation code or 2 is IMHO not a complication.

mas does not know, and should not know that there are "special" projects in GCP that have no quota at all. The only thing mash knows is "create the image over here and test it over there" that's a generic concept that we could even implement in the other cloud framework specializations if we wanted to.
