### ISSUE TITLE
download should make better effort

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#415]
It appears we give up too easily in the downloader producing

"Pass[1]: Error: MashImageDownloadException: Build number mismatch between me
tadata and image files"

We should tray harder, maybe with a 60 second sleep and 5 retries to give the build service a chance to post consistent data.

**Comment by smarlowucf** [comment]
This was a consideration in design. The decision being that it was unlikely for the metadata and image build numbers to be caught in flux.

This has happened multiple times already so the original consideration is incorrect and therefore we should add a retry mechanism.

**Comment by smarlowucf** [comment]
It may be more robust to have a ordered download as well. Guarantee the smaller files are downloaded prior to the image file. Give the time needed for image file it's more likely that the packages file gets updated in the middle of the process.
