### ISSUE TITLE
add the test log information to the mash log

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#418]
The integrated IPA test code writes by default to it's own log. In order to correlate a test failure in mash the user has to fish through the mash log and the ipa logs and make a manual correlation. To make this easier the ipa log names (full path) should appear in the mash log.

At present the mash log contains, for example

```
ERROR 2019-03-12 12:58:37,647 TestingService
    Pass[1]: Exception in testing: 'cn-north-1'
```

this makes it difficult to find the ipa logs to figure out the failure as other testing may run in parallel.

**Comment by smarlowucf** [comment]
This already is part of the log file (ipa results file for each account in a job). `Exception in testing` happens when an unhandled exception happens in a testing job. So the job did not finish.

**Comment by smarlowucf** [comment]
The bug that caused this to happen is #420 . Will close this as ipa results are already part of job log.
