### ISSUE TITLE
Better integration with mash and IPA

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#461]
When a job fails in testing during a mash run the user gets a pointer to the IPA test log. However, this log is a json file a difficult to parse without help. ipa has the "results show" functionality. However the user cannot use the information provided by mash directly with IPA. for example:

ipa results show /var/lib/mash/ipa/results/gce/sles-15-sap-v20190520/gce-ipa-test-bnvoa/20190520185124.results
Usage: ipa results show [OPTIONS] [ITEM]
Try "ipa results show --help" for help.

Error: Invalid value for "[ITEM]": /var/lib/mash/ipa/results/gce/sles-15-sap-v20190520/gce-ipa-test-bnvoa/20190520185124.results is not a valid integer

Because ipa expects an integer based on ipa list. However when multiple jobs run in parallel in mash the list indexes tend to change. Thus mash cannot provide index information. Maybe 'ipa results' should accept a full log file reference rather than only an index from an ever changing list. Or mash could extract the results from ipa and add them to the mash log if a job fails.

**Comment by smarlowucf** [comment]
IPA has:

```
ipa results show --results-file {location/of/results/file}
```

MASH should better parse and make available results/status, this is a TODO.

**Comment by rjschwei** [comment]
OK, thanks, maybe a quick fix/help for me and others is to put the full ipa command line in the mash log

**Comment by smarlowucf** [comment]
I think this is okay to close now. There is better integration with the img-proof logging and all json results files are reported in the job log. If there any new feature requests that are specific to this integration they can be added new bug reports.
