### ISSUE TITLE
root_swap support

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#471]
The goal of the root_swap support is to allow users to create an on-demand image outside the white listed account that supports billing code registration. This requires that the helper image is an on-demand image. In support of the implementation in #467 we need to support using a different helper AMI when using the root swap method vs the non root swap method. This allows for reduced cost image creation when the creation of on-demand images is not necessary.

That said it is a valid decision for us to say that the cost of using an on-demand image for image creation is negligible and therefore there is no need to have different helper AMIs in the config.

**Comment by smarlowucf** [comment]
Aren't the helper images Amzon Linux? Why does on-demand vs byos come in to play?

**Comment by smarlowucf** [comment]
Can this discussion be consolidated with #465?

**Comment by smarlowucf** [comment]
With root swap are the ami's specific to the image being uploaded? I.e. if you are uploading a sles 15 image via root swap does the helper ami need to be the most recent sles 15 image? If that's the case then this needs to be an option in job doc. Otherwise using a job doc override I think is also a good option.

`root_swap_ami` would be required if `use_root_swap` is `True`.

**Comment by smarlowucf** [comment]
The `root_swap_ami` option however becomes pretty complex because every region has a different ami id and a job might have multiple accounts.

**Comment by rjschwei** [comment]
> Can this discussion be consolidated with #465?

I figured #465 will be closed when #467 gets merged, if not then yes the issues can be combined.

**Comment by rjschwei** [comment]
> With root swap are the ami's specific to the image being uploaded? I.e. if you are uploading a sles 15 image via root swap does the helper ami need to be the most recent sles 15 image?

No, for creating a SLES on-demand one has to use a SLES on-demand helper instance, for SLES For SAP a SLES For SAP helper AMI has to be used. For SLES For SAP the version has to match, i.e. SLES For SAP 15 image requires a SLES For SAP 15 helper instance. This requirement does not exist for SLES.

> If that's the case then this needs to be an option in job doc. Otherwise using a job doc override I think is also a good option.
> 
> `root_swap_ami` would be required if `use_root_swap` is `True`.

**Comment by rjschwei** [comment]
> The `root_swap_ami` option however becomes pretty complex because every region has a different ami id and a job might have multiple accounts.

Correct. But the question is do we need to support this in the general sense? The only use case we have today is the openQA integration and in that case we know there is testing in one account and one region. So we could have a specific implementation.

1.) If root_swap in job do is True the user also has to specify a root_swap_ami in the job doc
2.) If root_swap_ami is set in the job doc we use it instead of the configured helper ami

This should be a reasonably straight forward implementation that covers the use case we have. If at some point in the future a more general approach is needed we can revisit he implementation. But the simple case we need should be reasonably straight forward  to cover.

**Comment by smarlowucf** [comment]
I'd rather push it in a single PR. But we can leave both issues open and close together.
