### ISSUE TITLE
mash needs to try harder

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#481]
Still getting too many failures with:

Job failed. The following error was logged: 

MashImageDownloadException: No image metadata found for image name: SLES15-SP1-EC2-HVM

The failure rate for this is probably in the 20% range.

While we want to have a speedy processing of the job we also have to try harder to avoid the user having to resubmit jobs due to temporal download issues.

**Comment by smarlowucf** [comment]
Migrated https://github.com/SUSE-Enceladus/img-downloader/issues/3
