### ISSUE TITLE
preferred subnet

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#482]
We should have a way to configure the use of a preferred subnet. If the subnet is available it should be used for uploading and testing. This can help to avoid the:

"""
Upload to Amazon EC2 failed with: An error occurred (VpcLimitExceeded) when calling the CreateVpc operation: The maximum number of VPCs has been reached.
"""
issue

**Comment by smarlowucf** [comment]
Todo: Add subnet option to job docs for GCE and EC2. This will be used by uploader service for helper instance and testing service.

**Comment by jgleissner** [comment]
I'm basically done implementing this for EC2. One question though, should we make the security group configurable too? It could be useful if you want to limit access to the instances spawned by mash for some reason.

**Comment by smarlowucf** [comment]
Note: I pushed changes to the schema which separates it from one large module to small independent modules. This will require merge/update in this branch.

**Comment by rjschwei** [comment]
> I'm basically done implementing this for EC2. One question though, should we make the security group configurable too? It could be useful if you want to limit access to the instances spawned by mash for some reason.

Well there is no limit we have run into w.r.t. security group creation and we need ssh access and that's all that is being opened. Last but not least the key is a temporary key generated on the fly. This makes the exposure pretty low. For someone concerned with access to the test instances via the Internet they can now specify a subnet in a VPC that is only accessible from the corporate network. With this I am not certain that further restriction via security group source IPs is really all that useful. Given our plate is full and we have no clear use-case I would say we table specification of the security group.

**Comment by smarlowucf** [comment]
Closed by #496
