### ISSUE TITLE
re-run test on temporal failures

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#483]
The test may fail due to resource limits, such as

```
RROR 2019-06-25 12:14:16,092 TestingService
    Pass[1]: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mash/services/testing/img_proof_helper.py", line 95, in img_proof_test
    timeout=img_proof_timeout
  File "/usr/lib/python3.6/site-packages/img_proof/ipa_controller.py", line 132, in test_image
    return cloud.test_image()
  File "/usr/lib/python3.6/site-packages/img_proof/ipa_cloud.py", line 644, in test_image
    self._launch_instance()
  File "/usr/lib/python3.6/site-packages/img_proof/ipa_gce.py", line 220, in _launch_instance
    **kwargs
  File "/usr/lib/python3.6/site-packages/libcloud/compute/drivers/gce.py", line 4017, in create_node
    self.connection.async_request(request, method='POST', data=node_data)
  File "/usr/lib/python3.6/site-packages/libcloud/common/base.py", line 772, in async_request
    response = request(**kwargs)
  File "/usr/lib/python3.6/site-packages/libcloud/compute/drivers/gce.py", line 121, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libcloud/common/google.py", line 808, in request
    *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python3.6/site-packages/libcloud/common/base.py", line 155, in __init__
    self.object = self.parse_body()
  File "/usr/lib/python3.6/site-packages/libcloud/common/google.py", line 296, in parse_body
    raise GoogleBaseError(message, self.status, code)
libcloud.common.google.GoogleBaseError: {'domain': 'usageLimits', 'reason': 'quotaExceeded', 'message': "Quota 'CPUS' exceeded. Limit: 50.0 in region us-west1."}
```

mash should classify this as a recoverable failure and re-run the tests in some other region.

**Comment by jgleissner** [comment]
AFAICS mash triggers tests in multiple regions, if the job definition has multiple `cloud_accounts` configured. Mash could consider hitting quota restrictions as soft errors and only fail if none of the tests succeed. Makes sense?

**Comment by smarlowucf** [comment]
For EC2 there can be multiple accounts per job. This is to upload the same image to aws, aws-cn and aws-us-gov in a single job. So all three should pass for a job to be successful.

For GCE and Azure there aren't multiple accounts so I plan to remove that function eventually as it is extra complication that doesn't serve a purpose.

**Comment by jgleissner** [comment]
@smarlowucf I used multiple account configurations with GCE, which all use the same `testing_account` but different regions to trigger multiple concurrent tests. So from that point of view it's actually useful IMO.

At any rate we'll need a way to configure multiple regions for this feature. I guess this could also be done in the job description. Whenever mash encounters a retryable error, it could just take the next region in the list and retry.

**Comment by smarlowucf** [comment]
> I used multiple account configurations with GCE, which all use the same `testing_account` but different regions to trigger multiple concurrent tests. So from that point of view it's actually useful IMO.

That's fair and that would work fine. My concern is that it would be very confusing. Then you are intermingling two different workflows into the EC2 concept of allowing multiple accounts per job. Being able to publish to aws, aws-cn, and aws-us-gov in a single job then becomes a problem because for EC2 all accounts should pass and for Azure/GCE only one needs to pass.

> At any rate we'll need a way to configure multiple regions for this feature. I guess this could also be done in the job description. Whenever mash encounters a retryable error, it could just take the next region in the list and retry.

It brings up many issues in relation to regions. The initial concept was that a user created an account and tied it to a specific region. That way the user knows where an image is being tested/uploaded etc and can make sure everything is in place. Such as having the network set up so the launched instance is accessible to mash.

IMHO the solution here has to be specific to each cloud. For GCE there's less issues with network and image upload/test region since most things are global. For EC2 this is the exact opposite and choosing a random region to failover to has a good chance of causing more problems.

**Comment by jgleissner** [comment]
Picking a region at random doesn't sound like a good idea, it should be under user control.

I guess for EC2 this retry feature isn't really going to work as image IDs are tied to regions. Even if you could provide a fallback region, you'd still have to add some magic to copy the image around first and update the image ID. And you'd need some extra knowledge in mash about the disconnected regions.

I believe Azure is similar as images are also region specific. So I suppose this is a GCE specific feature. I understand if you don't want to use the account configuration to implement it, as it would mean that it would behave differently in EC2 (all accounts must pass) and GCE (retryable error ok as long as one passes).

So IMO it would be best if we add another optional attribute to the GCE job description that allows configuration of fallback test regions.

**Comment by smarlowucf** [comment]
> Picking a region at random doesn't sound like a good idea, it should be under user control.

Agree.

> I guess for EC2 this retry feature isn't really going to work as image IDs are tied to regions. Even if you could provide a fallback region, you'd still have to add some magic to copy the image around first and update the image ID.

> I believe Azure is similar as images are also region specific. So I suppose this is a GCE specific feature. I understand if you don't want to use the account configuration to implement it, as it would mean that it would behave differently in EC2 (all accounts must pass) and GCE (retryable error ok as long as one passes).

Yeah, that is true. It would require the job go back to uploader service which we cannot do. Jobs only go one direction until they fail or finish.

> So IMO it would be best if we add another optional attribute to the GCE job description that allows configuration of fallback test regions.

That would work.

**Comment by jgleissner** [comment]
Feature was merged.
