### ISSUE TITLE
improve download issue reporting

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#484]
When we cannot fetch the metadata the notification to the user, via e-mail simply states that the metadata cannot be found. However, this may be the case due to an input error. While we cannot differentiate between "the file is not here because you pointed me in the wrong direction", and "the file is not on he server even it is supposed to be" we can help the user make that diagnostic by echoing information about where we were trying to get the data from.

For example, at the moment one may receive the following error:

```
MashImageDownloadException: No image metadata found for image name: SLES15-SP1-EC2-HVM
```

However since by necessity the configuration of the name of the image and the path were to get it from are separate this message only conveys 1/2 the information to the user. We shold include where the code was trying to get the image from. For example:

```
MashImageDownloadException: No image metadata found for image name: SLES15-SP1-EC2-HVM in location https://.......
```

That will give the user an easy way to reproduce in the browser or via wget etc and help themselves in a more direct an obvious way.

While the data the user needs is in the job doc correlating the information from the e-mail to the job doc requires fishing for the uuid and that's not nice.

**Comment by smarlowucf** [comment]
This will be captured in the new image downloader package.

**Comment by smarlowucf** [comment]
Migrated https://github.com/SUSE-Enceladus/img-downloader/issues/2
