### ISSUE TITLE
SUMa support

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#493]
As of SUMa 4.0 the baseproduct link does no longer point to the underlying SLES product file, but there is a SUMa product file.

mash and img-proof need to support this case, i.e. we still want to upload and release images that contain SUMa. At present test would fail in img-proof due to the baseproduct link. mash needs to accept a new parameter to pass onto img-proof and img-proof needs to accept a baseproduct link that does not point to SLES/SLE_SAP

**Comment by smarlowucf** [comment]
I think there's more discussion needed here. Neither MASH nor img-proof have been updated to fully support testing SUMA specifically.

If SUMA needs a different case to handle baseproduct test then we may want to start a new test description for SUMA such as we have for test_sles_sap.

**Comment by rjschwei** [comment]
We are not going to want to run SUMa specific tests. There are no smoke tests in SUMa that would be appropriate in the sense of a "smoke test" before release. Therefor yes, it could be as easy as creating a  test_suma, case that looks for the proper baseproduct link

We also have to confirm that there is no other test that would trip over the baseproduct link being different. For SUMa we'd still want to run the basic SLES BYOS smoke tests, boot, ssh connect, reboot etc.

**Comment by smarlowucf** [comment]
> At present test would fail in img-proof due to the baseproduct link.

What test would fail? Looking at the current test suite there's nothing I see that would fail. We have a way to get what baseproduct points to but that's only used to determine if an image is SAP. And that is only used for getting the repos for SMT. All of this will change when RMT is in place. Aside from this general repo test change I don't see where changes are needed at this point for SUMA.

**Comment by rjschwei** [comment]
Great, thanks. Obviously what was in my head about how things worked and what is implemented are different.
