### ISSUE TITLE
Consider renaming mash? (collision with another mash tool)

### ISSUE THREAD

**Issue by Conan-Kudo** [SUSE-Enceladus/mash#664]
As part of investigating tools on the behalf of the Fedora Cloud SIG for handling uploads of Fedora Cloud Edition images to all the public clouds (our current tool restricts us only to AWS EC2, and we want to support all of them now), I found this tool.

However, there is a _slight_ unfortunate problem. The name collides with an existing [`mash`](https://pagure.io/mash) used to produce RPM repos from a collection of packages built in Koji.

Would you consider renaming this project to eliminate confusion?

**Comment by Conan-Kudo** [comment]
cc: @dustymabe @major

**Comment by rjschwei** [comment]
Thanks for pointing out the conflict, but no, mash will not be renamed.
