### ISSUE TITLE
Error uploading images to Azure. Exception in upload: Image file not found. Ensure the path to the file is correct." But the file exists in the given path

### ISSUE THREAD

**Issue by Akatama** [SUSE-Enceladus/mash#927]
Hey!

I recently pulled the most recent version of mash from the openSUSE registry, and I have found then when I try to upload the images, I get an exception during the Mash job. Here is the full error:

`Exception in upload: Image file /var/lib/mash/images/88c3613a-3eec-4ceb-ba99-92b2b53d439e/openSUSE-Tumbleweed.x86_64-16.0.0-Cloud-Base-Azure-BuildTW.16.0.145.vhdfixed.xz not found. Ensure the path to the file is correct.`

As stated in the title, if I go to that path in the Mash container, that image file indeed exists. I had tried this last back in August, and at that time, everything worked with Azure, including the image upload to the Storage Account.

I had been planning to try to take a look myself at this error further, but I have been under the weather the last few days and tomorrow I am hosting Thanksgiving. It is possible I might have some time to look at it this weekend or early next week, but I thought I would write this bug now.
[azure_x86_64.txt](https://github.com/user-attachments/files/17943856/azure_x86_64.txt)

**Comment by Akatama** [comment]
@smarlowucf After doing some research, I have found the issue. It is not an issue with mash itself, but rather the container image from registry.opensuse.org/virtualization/appliances/images/images_tw/opensuse/mash:latest is missing the bash file command. I will close this issue soon, but can you point me to where the Dockerfile or Containerfile is that builds this container? Since its primarily a Mash container I would've assumed it would be in this repo, but I can't seem to find it.

Here is how I found out:

I tracked down to where the error was being thrown as line 85 in mash/services/upload/azure_job.py. This line calls upload_image_blob from azure_img_utils/azure_image.py which on line 183 calls this:
![upload_image_blob](https://github.com/user-attachments/assets/579866e1-811d-4e8e-8a70-5d2199ee2042)

if I try to call FileType from the python REPL in the mash container, I get a different error than what mash reports:
![FileType_Error](https://github.com/user-attachments/assets/70e5ff4c-8dd6-40a5-8615-d02524b7dff5)

Note that 'file' has no such file or directory, not the image file. If you look in mash/services/upload/azure_job.py, you will se that this exception is handled there and that is where the error message I reported above is generated.

We can confirm that azure_img_utils/filetype.py calls the 'file' bash command by looking on line 32:
![FileType_code](https://github.com/user-attachments/assets/77396e9e-8b4c-4481-abd6-21aaa4153a34)

Finally, if I try to find where the filetype command is located in the container, I can see it can't be found. I did an example of a command I knew existed in the container, just to confirm for myself that this method of searching for bash commands works:
![file_command_does_not_exist](https://github.com/user-attachments/assets/8b3775b2-e933-406f-8137-a993848a9d6c)

**Comment by smarlowucf** [comment]
Hi @Akatama the image is built in the open build service using Kiwi https://build.opensuse.org/package/show/Virtualization:Appliances:Images/mash-image-docker. I noticed there are a couple issues with the image at the moment so I will work on fixing those including adding the file package.

**Comment by Akatama** [comment]
You're welcome! Thank you for responding so quickly.

 I will try to take a look too, but I suspect that you will be better able to fix any of the other issues with the image.

**Comment by Akatama** [comment]
@smarlowucf I saw the last person to make changes to the Mash build on OBS was Marcus Schafer. Coincidentally, he is also working on the openSUSE Cloud Project, so I asked him to either take a look or tell me where I could make changes (I am not that familiar with OBS, but for the VM images we use for openSUSE Cloud, we use OBS to build an image and have a repo on openSUSE Pagure where we can make changes, and I could not find the equivalent repo for Virtualization:Apliances:Images). 

Anyway, it appears he fixed it as the build is passing now. I am about to try out the new image. He did tell me to tell you this:

"The mash container is building again. I had to do some hacks to the python3-img-proof package to build as a python package for TW and it also seems that pytest-json-report no longer exists. I could not find this module anywhere in suse and img-proof also doesn't build in its devel project anymore for that reason. I wonder how they tested the functionality. So far I dropped the support for this json reporting and can't estimate the impact of the change. However for our use case here the mash jobs defines "last_service": "create" which is imho upload and creation of an image in the cloud, test and publishing would follow which means I believe we are not using any img-proof tests at the moment"

I took a look at PyPI and I see pytest-json-report package exists, although it was last updated in March of 2022 and only supports up to Python 3.10. From what I can see this seems to be the missing package though. Let me know if that is incorrect.

**Comment by smarlowucf** [comment]
Hi @Akatama it looks like the container now has the file package included. Does that fix your issue? The pytest json report package is required by mash to run tests on the created image. I will work on a temporary fix for that package and look into a longer term solution.

**Comment by Akatama** [comment]
Yes it does. Closing the bug. Thanks for your help!
